version: '3' # composeファイルのバーション指定

services:
    app: # service名
        build: . # ビルドに使用するDockerfileがあるディレクトリ指定
        tty: true # コンテナの起動永続化
        volumes:
            - .:/go/src/app:cached # マウントディレクトリ指定
        ports:
           - "8000:8000" #golang webserver用のポート
           - "5050:5050" #delve用のポート
        privileged: true # Delveで必要なので付与します。セキュリティ面から本番環境では使うべきではありません。
        command: /bin/sh -c "while sleep 1000; do :; done" & dlv debug --headless --listen=:5050 --log
        environment:
            - "TZ=Japan"